### ISSUE TITLE
Questions about the saved checkpoints and the evaluation strategy

### ISSUE THREAD

**Issue by yifliu3** [CuiRuikai/Partial2Complete#2]
Hi, 

I'm very interested in your great work, and I find the provided checkpoints on 3D-EPN datasets have one model for each category. Since I do not observe the corresponding code, I'm curious if you saved the best checkpoints for each category, i.e., the checkpoints at the 50-th epoch performs the best for the chair category, so you preserve it and name it as the checkpoints for the chair?

If so, I'm wondering if you're doing the same strategy during the evaluation procedure, which may raise the unfair comparision problem.

**Comment by CuiRuikai** [comment]
Hi Yifan,

Each checkpoint is the one with the best performance. There are trained with different config.yaml files as provided. This approach follows previous works including PoinTr and Cycle4Completion, etc. Let me know if you have further concerns.
________________________________
From: Yifan LIU ***@***.***>
Sent: Sunday, September 3, 2023 16:13
To: CuiRuikai/Partial2Complete ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [CuiRuikai/Partial2Complete] Questions about the saved checkpoints and the evaluation strategy (Issue #2)


Hi,

I'm very interested in your great work, and I find the provided checkpoints on 3D-EPN datasets have one model for each category. Since I do not observe the corresponding code, I'm curious if you saved the best checkpoints for each category, i.e., the checkpoints at the 50-th epoch performs the best for the chair category, so you preserve it and name it as the checkpoints for the chair?

If so, I'm wondering if you're doing the same strategy during the evaluation procedure, which may raise the unfair comparision problem.

**Comment by yifliu3** [comment]
Got it. Thanks a lot for your prompt reply!
